const routes = {
    root:"/",
    login:"/login",
    signout:"/signout",
    landing:"/landing",
    pageNotFound:"*",
    jobRequest:"/job-request",
    jobRequestDetails:"/job-details",
    datatables:"/tables",
    forms:"/forms",
    themeSettings:"/theme-settings",
    analytics:"/analytics",
    users:"/users",
    settings:"/settings",
    createUser:"/create-user",
    clientOnBoarding:"/client-onboarding",
    worksheet:"/worksheets",
    userMaster:"/master-data",
    userProfile:"/user-profile",
    worksheetNew:"/worksheets/new",
    worksheetEdit:"/worksheets/edit",
    worksheetDetails:"/worksheet-details",
    worksheetReport:"/worksheet-report",
    healthCheck:"/health-check",
    joblisting:"/job-listing",
    reportImages:"/report-images",
    previousReport:"/previous-reports",
    privileges: "/privileges"
}

export default routes